---

- name: Install Base Packages
  apt:
    pkg: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - git
      - software-properties-common
    state: present
    update_cache: true
