- name: packer ami
  hosts: all
  become: True
  gather_facts: True
  tasks:
        
    - name: install docker
      include_role: 
        name: docker
    
    # - name: cloudwatch instance monitoring
    #   include_role:
    #     name: cloudwatch
    
    # - name: aws logs
    #   include_role:
    #     name: awslogs
    #   vars:
    #     awslogs_config:
    #       - file: /var/log/syslog
    #         datetime_format: "%b %d %H:%M:%S"
    #         log_group_name: syslog

