- name: packer ami
  hosts: all
  become: True
  gather_facts: True
  tasks:

    # it takes a minute for apt-get and
    # some other network resources to
    # start working
    - pause:
        minutes: 1

    - name: install base packages
      apt:
        pkg:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: make python link
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        owner: root
        group: root
        state: link

    # - name: install cloudwatch_agent
    #   include_role:
    #     name: cloudwatch_agent
    #   vars:
    #     awslogs_config:
    #       - file: /var/log/syslog
    #         datetime_format: "%b %d %H:%M:%S"
    #         log_group_name: syslog

    - name: Remove package cache, and deps no longer required
      apt:
        autoclean: yes
        autoremove: yes
