- name: packer ami
  hosts: all
  become: True
  gather_facts: True
  tasks:
    # - name: include vault secrets
    #   include_vars:
    #     file: vault.yml
            
    - name: postgres up
      include_role:
        name: postgres
    
    # - name: dump django clone
    #   postgresql_db:
    #     login_host: djangoclone.build-ops.in.accuenplatform.com
    #     login_user: accuen
    #     login_password: "{{ vault_pg_password }}"
    #     name: django
    #     state: dump
    #     target: /tmp/django.sql
    
    # - name: restore django clone locally
    #   postgresql_db:
    #     name: django
    #     state: restore
    #     target: /tmp/django.sql
    
    # - name: remove dump
    #   file:
    #     path: /tmp/django.sql
    #     state: absent

    # - name: cloudwatch instance monitoring
    #   include_role:
    #     name: cloudwatch
    
    # - name: aws logs
    #   include_role:
    #     name: awslogs
    #   vars:
    #     awslogs_config:
    #       - file: /var/log/syslog
    #         datetime_format: "%b %d %H:%M:%S"
    #         log_group_name: syslog

    # - name: build the database
    #   include_role:
    #     name: clone_smp