version: '3'
services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_USER: airflow
      POSTGRES_DB: airflow
    # volumes:
    # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # - ./postgres:/var/lib/postgresql/data
    # healthcheck:
    #   test: [ "CMD", "pg_isready", "-q", "-d", "airflow", "-U", "airflow"]
    #   timeout: 45s
    #   interval: 10s
    #   retries: 10

  airflow:
    build: .
    #image: "annalect/airflow:1.10.3"
    depends_on:
      - db
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://airflow:airflow@db/airflow
    command: sh /usr/local/airflow/run.sh
    volumes:
      - .:/opt/local/src
    links:
      - db
  # initer:
  #   build: .
  #   volumes:
  #     - .:/opt/local/src
