---

- name: Install Base Packages
  apt:
    pkg: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - git
      - software-properties-common
    state: present
    update_cache: true

- name: add docker gpg key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    update_cache: yes

- name: install docker
  apt:
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present

- name: add user to docker group
  user:
    name: ubuntu
    append: yes
    groups: 
      - docker